#!/usr/bin/env bash

########################################
# Catppuccin Mocha Colors
########################################

TEXT=0xffcdd6f4
SUBTEXT0=0xffa6adc8
MAUVE=0xffcba6f7
PEACH=0xfffab387

PADDINGS=3

########################################
# Paths
########################################

PLUGIN_DIR="$CONFIG_DIR/plugins"

########################################
# Bar
########################################

sketchybar --bar \
  position=top \
  height=32 \
  blur_radius=30 \
  color=0xaa181825 \
  shadow=on \
  sticky=on \
  margin=100 \
  y_offset=0 \
  corner_radius=10 \
  border_width=0

########################################
# Defaults (NO BACKGROUNDS)
########################################

default=(
  padding_left=10
  padding_right=10

  icon.font="Hack Nerd Font:Bold:16.0"
  label.font="Hack Nerd Font:Bold:14.0"

  icon.color=$TEXT
  label.color=$TEXT

  background.drawing=off

  icon.highlight_color=$MAUVE
)

sketchybar --default "${default[@]}"

########################################
# Workspace event
########################################

sketchybar --add event aerospace_workspace_change

########################################
# Workspaces (flat style)
########################################

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
      icon="$sid" \
      icon.color=$SUBTEXT0 \
      label.drawing=off \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_DIR/aerospacer.sh $sid"
done

########################################
# Front App
########################################

sketchybar --add item front_app left \
  --set front_app \
    icon.drawing=off \
    label.color=$TEXT \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

########################################
# Clock
########################################

sketchybar --add item clock right \
  --set clock \
    icon=󰥔 \
    icon.color=$TEXT \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

########################################
# Volume
########################################

sketchybar --add item volume right \
  --set volume \
    icon.color=$GREEN \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

########################################
# Battery
########################################

sketchybar --add item battery right \
  --set battery \
    icon.color=$PEACH \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    update_freq=120 \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

########################################
# Refresh
########################################

sketchybar --update
