#!/usr/bin/env bash

########################################
# Catppuccin Mocha Colors
########################################

BASE=0xff1e1e2e
MANTLE=0xff181825
CRUST=0xff11111b

SURFACE0=0xff313244
SURFACE1=0xff45475a

TEXT=0xffcdd6f4
SUBTEXT0=0xffa6adc8
OVERLAY0=0xff6c7086

BLUE=0xff89b4fa
MAUVE=0xffcba6f7
LAVENDER=0xffb4befe
GREEN=0xffa6e3a1
PEACH=0xfffab387

PADDINGS=3

########################################
# Paths
########################################

PLUGIN_DIR="$CONFIG_DIR/plugins"

########################################
# Bar
########################################

sketchybar --bar \
  position=top \
  height=32 \
  blur_radius=30 \
  color=0xaa181825 \
  shadow=on \
  sticky=on \
  margin=100 \
  y_offset=0 \
  corner_radius=10 \
  border_width=0

########################################
# Defaults (NO BACKGROUNDS)
########################################

default=(
  padding_left=10
  padding_right=10

  icon.font="Hack Nerd Font:Bold:16.0"
  label.font="Hack Nerd Font:Bold:14.0"

  icon.color=$TEXT
  label.color=$TEXT

  background.drawing=off

  icon.highlight_color=$BLUE
)

sketchybar --default "${default[@]}"

########################################
# Workspace event
########################################

sketchybar --add event aerospace_workspace_change

########################################
# Workspaces (flat style)
########################################

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
      icon="$sid" \
      icon.color=$SUBTEXT0 \
      label.drawing=off \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_DIR/aerospacer.sh $sid"
done

########################################
# Front App
########################################

sketchybar --add item front_app left \
  --set front_app \
    icon.drawing=off \
    label.color=$PEACH \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

########################################
# Clock
########################################

sketchybar --add item clock right \
  --set clock \
    icon=󰥔 \
    icon.color=$TEXT \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

########################################
# Volume
########################################

sketchybar --add item volume right \
  --set volume \
    icon.color=$GREEN \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

########################################
# Battery
########################################

sketchybar --add item battery right \
  --set battery \
    icon.color=$PEACH \
    icon.padding_right=$PADDINGS \
    label.color=$TEXT \
    label.padding_left=$PADDINGS \
    update_freq=120 \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

########################################
# Refresh
########################################

sketchybar --update
